version: "3"

networks:
  hl-lab3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  redis-master:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.4
    volumes:
      - ./redis-master:/redis
    command: redis-server /redis/redis.conf
    restart: always
    ports:
      - 6380:6380

  redis-replica-0:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.5
    volumes:
      - ./redis-replica-0:/redis
    command: redis-server /redis/redis.conf
    restart: always
    ports:
      - 6381:6381

  redis-replica-1:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.6
    volumes:
      - ./redis-replica-1:/redis
    command: redis-server /redis/redis.conf
    restart: always
    ports:
      - 6382:6382